
---MERGE IS THE COMBINATION OF INSERT,DELETE AND UPDATE STATEMENTS



CREATE TABLE EMPLOYEE_TARG
( 
       E_ID INT PRIMARY KEY,
	   E_NAME CHAR(20),
	   E_SALARY INT,
	   E_AGE INT,
	   E_GENDER CHAR(10),
	   E_DEPT CHAR(30)
)

CREATE TABLE EMPLOYEE_SOURCE
( 
       E_ID INT PRIMARY KEY,
	   E_NAME CHAR(20),
	   E_SALARY INT,
	   E_AGE INT,
	   E_GENDER CHAR(10),
	   E_DEPT CHAR(30)
)

INSERT INTO EMPLOYEE_TARG VALUES(1,'SAM',93000,40,'MALE','OPERATIONS');
INSERT INTO EMPLOYEE_TARG VALUES(2,'BOB',80000,21,'MALE','SUPPORT');
INSERT INTO EMPLOYEE_TARG VALUES(3,'ANNE',130000,25,'FEMALE','ANALTYICS');
INSERT INTO EMPLOYEE_TARG VALUES(6,'JEFF',112000,27,'MALE','OPERATIONS');
INSERT INTO EMPLOYEE_TARG VALUES(7,'ADAM',100000,28,'MALE','CONTENT');
INSERT INTO EMPLOYEE_TARG VALUES(8,'PRIYA',85000,37,'FEMALE','TECH');

SELECT * FROM EMPLOYEE_TARG;

INSERT INTO EMPLOYEE_SOURCE VALUES(1,'SAM',95000,45,'MALE','OPERATIONS');
INSERT INTO EMPLOYEE_SOURCE VALUES(2,'BOB',80000,21,'MALE','SUPPORT');
INSERT INTO EMPLOYEE_SOURCE VALUES(3,'ANNE',125000,25,'FEMALE','ANALTYICS');
INSERT INTO EMPLOYEE_SOURCE VALUES(4,'JEFF',73000,30,'FEMALE','ANALTYICS');
INSERT INTO EMPLOYEE_SOURCE VALUES(5,'ADAM',159000,33,'MALE','SALES');
INSERT INTO EMPLOYEE_SOURCE VALUES(6,'PRIYA',112000,27,'FEMALE','OPERATIONS');


SELECT * FROM EMPLOYEE_SOURCE;

MERGE EMPLOYEE_TARG AS T
USING EMPLOYEE_SOURCE AS S
     ON T.E_ID=S.E_ID
WHEN MATCHED
     THEN UPDATE SET T.E_SALARY=S.E_SALARY,T.E_AGE=S.E_AGE
WHEN NOT MATCHED
     THEN INSERT (E_ID,E_NAME,E_SALARY,E_AGE,E_GENDER,E_DEPT)
	 VALUES(S.E_ID,S.E_NAME,S.E_SALARY,S.E_AGE,S.E_GENDER,S.E_DEPT)
WHEN NOT MATCHED BY SOURCE
     THEN DELETE;

SELECT * FROM EMPLOYEE_TARG;
